name: Deploy Flask App to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /var/www/my-flask-app
          
          # 코드 업데이트
          git pull origin main
          
          # 가상환경 활성화 및 의존성 업데이트
          source venv/bin/activate
          pip install -r requirements.txt
          
          # 기존 Flask 앱 프로세스 종료
          sudo pkill -f "python.*app.py" || true
          
          # 새 Flask 앱 백그라운드 실행
          nohup python3 app.py > app.log 2>&1 &
          
          # 잠시 대기 후 프로세스 확인
          sleep 3
          ps aux | grep python
          
          echo "Deployment completed successfully!"
